// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bntvjimzusvnjtnurzsk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJudHZqaW16dXN2bmp0bnVyenNrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTQ0MjksImV4cCI6MjA3MTUzMDQyOX0.1rkc6EuDLKFzP4378gBDttiKS-mTXgzFpyNEpjMmfxQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});